
version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run eslint
workflows:
    install-and-lint:
      jobs:
        - lint:
          filters:
            branches:
              ignore:
                - CD-experimental-branch